Spreadsheet Cache with Redis
MeetMangrove/mangrove-website pull request #38
Opened 2018-01-23 13:13 UTC by lourou

2018-01-24 09:13 UTC, davb requested changes

2018-01-24 09:13 UTC, davb commented on middleware/redis_store.js
> +function redisStore(args) {
@lourou looks like you wrote your own Redis store, why didn't you use https://www.npmjs.com/package/cache-manager-redis ?
Also, you should connect to Redis by the env variable `REDIS_URI`, like in [`routes/index.js` here](https://github.com/MeetMangrove/mangrove-website/pull/38/files#diff-bb503f3d9047bcd4a5730559f1e16560R6) or it wont work on Heroku! Let me know if that's not clear!

2018-01-24 12:04 UTC, lourou commented
@davb Custom Redis store found in an issue on the main repo. Now switched to `cache-manager-redis` package. Deployment now works on Heroku!

2018-01-28 20:16 UTC, davb approved these changes

2018-01-28 20:16 UTC, merged